config/routes.rb
Resistivity::Application.routes.draw do
  get "grids/new"
  get "grids/edit"
  get "logout" => "sessions#destroy", :as => 'logout'
  get "login" => "sessions#new", :as => 'login'
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :users
  resources :sessions
  resources :surveys do
    resources :grids
  end
  
end

app/models/grid.rb
class Grid < ActiveRecord::Base
  belongs_to :survey  
end 

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :grid
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :survey
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end      
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  
  def new
    @survey = Survey.find(params[:survey_id])
    @grid = Grid.new
  end

  def create
    @row = ''
    @rownumber = 0
    params.each do |k,v|
      unless ['utf8','authenticity_token','survey_id','grid_x'].include? k then
        v == "" ? v = 0 : v = v.to_s
        if k.split("|")[1].to_i < params[:grid_x].to_i
          @row << v.to_s+","
        else
          @row << v.to_s
          @grid = Grid.new({"row"=>@row,"rownumber"=>@rownumber+=1,"survey_id"=>params[:survey_id]})
          @grid.save
          @row = ''
        end         
      end  
    end
    redirect_to survey_path(params[:survey_id])     
  end   
  
  def edit
    @survey = Survey.find(params[:survey_id])
    @grid = Grid.find_all_by_survey_id(params[:survey_id])
    @grid.sort! {|a,b| a.rownumber<=>b.rownumber}
  end
  
  def update
    @hash = {}
    @cols = []
    params.each do |k,v|
      if k.include? "|"
        @cols << k.split("|")[1].to_i
      end 
      v == "" ? v = 0 : v = v.to_s
    end
    @cols.max()
    @rownumber = 0
    @row = ''
    params.each do |k,v|
      if k.include? "|"
        if k.split("|")[1].to_i < @cols.max()
          @row << v.to_s+","
        else
          @row << v.to_s
          @rownumber += 1
          @grid = Grid.find_by_id(k.split("|")[0])
          @grid.row = @row
          @grid.rownumber = @rownumber
          @grid.save
          @row = ''
        end  
      end
    end
    redirect_to survey_path(params[:survey_id]) 
  end

  private
  
  def grids_params
    params.require(:grid).permit(:id,:survey_id,:row,:rownumbers)
  end
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "login"
  
  def new
    redirect_to surveys_path unless session[:user_id].nil?
  end
  
  def create
    user = User.authenticate(params[:email],params[:password])
    if user
      session[:user_id] = user.id
      redirect_to surveys_path
    else
      flash[:notice] = "invalid email or password"
      render "new"
    end    
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
     if session[:user_id].nil?
       redirect_to login_path
     else
        @user = User.find(session[:user_id])
        @surveys = Survey.find_by(user_id: session[:user_id]) 
     end 
  end  
  
  def show
    @survey = Survey.find(params[:id])
    unless @survey.grid.empty? then
      @array = []
      @sorted = @survey.grid.sort {|a,b| a.rownumber<=>b.rownumber}
      @sorted.each do |r|
        data = r.row.split(",")
        data.each do |d| @array << d end
      end
      @normalise = 255/@array.max.to_i
      @y = 30
    end 
  end
  
  def new
    @survey = Survey.new
  end
  
  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to @survey
    else
      render 'new'
    end    
  end 
  
  def edit
    @survey = Survey.find(params[:id])
  end  
  
  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to surveys_path
    else
      render 'edit'
    end          
  end     

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_path
  end  

  private
  
  def survey_params
    params.require(:survey).permit(:id,:user_id,:site,:date,:surveyors,:gridx,:gridy)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "login"
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up"
    else
      render "new"
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/grids/_gridsnav.html.erb
<div id="navwrapper">
  <% case controller.action_name %>
    <% when 'new' %> 
      <div class="navitem">
        <%= link_to image_tag('home.png', :class => 'icon'), surveys_path %><br />
        <%= link_to 'Home', surveys_path, :class => 'icon' %>
      </div>
      <div class="navitem">
        <%= image_submit_tag('save.png', :class => 'icon') %><br />
        <%= link_to 'Save', new_survey_grid_path(@survey), :class => 'icon' %>
      </div>
      
    <% when 'edit' %>
      <div class="navitem">
        <%= link_to image_tag('home.png', :class => 'icon'), survey_path(@survey) %><br />
        <%= link_to 'Home', survey_path(@survey), :class => 'icon' %>
      </div>
      <div class="navitem">
        <%= image_submit_tag('save.png', :class => 'icon') %><br />
        <%= submit_tag 'Update', :class => 'icon' %>
      </div>           
    <% else %>
      <p>No page</p> 
  <% end %>
</div>

app/views/grids/create.html.erb
<%= debug(@save) %>

app/views/grids/edit.html.erb
<%= @debug %>
<%= form_for @grid, :url => survey_grid_path, method: :put do |f| %>
  <input type="hidden" name="grid_x" value="<%= @grid.length %>">
  <% r=1 %>
  <% @grid.each do |d| %>
    <% i=1 %>
    <% d.row.split(",").each do |v| %>
      <input name="<%= d.id.to_s + '|' + i.to_s %>" value="<%= v %>" size="2">
      <% i+=1 %>
    <% end %>
    * <%= r %><br />
    <% r+=1 %>
  <% end %>
<hr />  
<%= render 'gridsnav' %>
<% end %>

app/views/grids/new.html.erb
<%= form_for([@survey, @survey.grid.build]) do |f| %>
  <input type="hidden" name="survey_id" value="<%= @survey.id %>">
  <input type="hidden" name="grid_x" value="<%= @survey.gridx %>">
  <% r=1 %>
  <% @survey.gridy.times do %>
    <% i=1 %>
      <% @survey.gridx.times do %>
        <input name="<%= r.to_s + '|' + i.to_s %>" size="3" class="input-grid">
        <% i+=1 %>
      <% end %>
      *<br />
    <% r+=1 %>
  <% end %>
<hr />
  <%= render 'gridsnav' %>
<% end %>

app/views/grids/update.html.erb
<%=  %>
<%= @hash %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resitivity.Guru</title>
  <link href='http://fonts.googleapis.com/css?family=News+Cycle|Fredericka+the+Great' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", "jquery-ui-1.10.4.custom.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery-1.11.1.min.js", "jquery-ui-1.10.4.custom.min.js", "canvas2image.js", "base64.js", "application.js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body> 
    <div id="user_nav">
      <% if current_user %>
        <%= current_user.email %> | <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Create Account", sign_up_path %>
      <% end %> 
    </div>
    <hr />  
    <h2><%= flash[:notice] %></h2>
    <%= yield %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resitivity.Guru</title>
  <link href='http://fonts.googleapis.com/css?family=News+Cycle|Fredericka+the+Great' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", "jquery-ui-1.10.4.custom.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery-1.11.1.min.js", "jquery-ui-1.10.4.custom.min.js", "application.js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body> 
  
    <div style="background-image:url('/assets/images/Resiguru.png');height:300px;">
        <h1 style="color:#fff;font-size:5em;margin:auto;padding: 50px 0px 0px 50px;">Resistivity.Guru</h1>
    </div>
 
    <div id="user_nav">
      <% if current_user %>
        <%= current_user.email %> | <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Create Account", sign_up_path %>
      <% end %> 
    </div>
    <hr />  
    <h2 style="text-align:center;"><%= flash[:notice] %></h2>
    <%= yield %>
    <p style="width:45%;float:left;">Electrical resistance surveys, also called earth resistance or resistivity surveys, are one of a number of methods used in archaeological geophysics. In this type of survey electrical resistance meters are used to detect and map subsurface archaeological features and patterning. This site renders the data readings of these surveys into coloured maps.</p>
  </div>
</body>
</html>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <%= hidden_field_tag 'survey[user_id]', session[:user_id] %>
  <table class="form">
    <tr><td class="r">Name of Site</td><td class="l"><%= f.text_field :site , size: 25 %></td></tr>
    <tr><td class="r">Date of Survey</td><td class="l"><%= f.date_field :date %></td></tr>
    <tr><td class="r">Name of Surveyor</td><td class="l"><%= f.text_field :surveyors, size: 25 %></td></tr>
    <tr><td class="r">Width of Grid <%= f.text_field(:gridx, size: 3) %></td><td class="l">Number of Rows <%= f.text_field(:gridy, size: 3) %></td></tr>
  </table>
<hr />
<%= render 'navwrapper'%>   
<% end %>  

app/views/surveys/_navwrapper.html.erb
<div id="navwrapper">
  <% case controller.action_name %>  
    <% when 'index' %>
      <div class="navitem">
        <%= link_to image_tag('grid.png', :class => 'icon'), new_survey_path %><br />
        <%= link_to 'Survey', new_survey_path, :class => 'icon' %>
      </div>      
    <% when 'new' %> 
      <div class="navitem">
        <%= link_to image_tag('home.png', :class => 'icon'), surveys_path %><br />
        <%= link_to 'Home', surveys_path, :class => 'icon' %>
      </div>
      <div class="navitem">
        <%= image_submit_tag('save.png', :class => 'icon') %><br />
        <%= link_to 'Save', surveys_path, :class => 'icon' %>
      </div>
    <% when 'show' %>
      <% if @survey.grid.present? %>
        <div class="navitem">
          <%= link_to image_tag('home.png', :class => 'icon'), surveys_path %><br />
          <%= link_to 'Home', surveys_path, :class => 'icon' %>
        </div>      
        <div class="navitem">
          <%= link_to image_tag('grid.png', :class => 'icon'), edit_survey_grid_path(@survey,@survey.grid.last.id) %><br />
          <%= link_to 'Edit', edit_survey_grid_path(@survey,@survey.grid.last.id), :class => 'icon' %>
        </div>
        <div class="navitem">
          <%= link_to image_tag('save.png', :id => 'download', :class => 'icon'), nil %><br />
          <%= link_to 'DownLoad', nil, :id => 'download-link', :class => 'icon' %>
        </div>        
      <% else %>
        <div class="navitem">
          <%= link_to image_tag('home.png', :class => 'icon'), surveys_path %><br />
          <%= link_to 'Home', surveys_path, :class => 'icon' %>
        </div> 
        <div class="navitem">
          <%= link_to image_tag('grid.png', :class => 'icon'), new_survey_grid_path(@survey) %><br />
          <%= link_to 'Add', new_survey_grid_path(@survey), :class => 'icon' %>
        </div>                
      <% end %>
    <% else %>
      <p>No page</p>  
  <% end %>
  
</div>

app/views/surveys/edit.html.erb
<%= render 'form' %>

app/views/surveys/index.html.erb
<h1>Welcome <%= @user.email.split('@',2)[0] %></h1>
<% if @surveys.nil? %>
  <p class="section">You don't have any Surveys Yet.</p>
<% else %>
<p class="section">Your Resistivity Surveys</p>
<ul>
  <% @surveys.each do |s| %>
  <li>
    <h2><%= link_to s.site, survey_path(s.id) %>  <div style="font-size:50%;display:inline;"><%= link_to '[delete]', survey_path(s.id), method: :delete, data: { confirm: 'Are you sure?' } %></div></h2>
  </li>
  <% end %>
</ul>
<% end %> 
<hr>
<%= render 'navwrapper' %>

app/views/surveys/new.html.erb
<%= render 'form' %>

app/views/surveys/show.html.erb
<h2><%= @survey.site %> | <%= @survey.date %></h2>
<% if @survey.grid.empty? %>
  <div id="gridWrapper">
    <h2>A visualisation of your data will appear here</h2>
  </div>
<% else %>
  <div id="gridWrapper">
    <canvas id="grid" width="<%= @survey.gridx*30 %>" height="<%= @survey.gridy*30+30 %>"></canvas>
  </div>
  
  <% @sorted.each do |r| %>
    <% @row = [] %>
    <% r.row.split(",").each do |num| %>
      <% @row.push(num.to_i) %>
    <% end %>
      <script>
        var canvas = document.getElementById('grid');
        var context = canvas.getContext('2d');
        var normalise = <%= @normalise %>;
        var array = <%= @row.to_json %>;
        var x = 0;
        for(var i=0;i < array.length;i++){
          context.beginPath();
          context.strokeStyle="rgb(0,0," + array[i]*normalise + ")";
          context.moveTo(x, <%= @y %>);
          context.lineTo(x+30, <%= @y %>);
          context.lineWidth = 30;
          context.stroke();
          x = x+30;
        }
      </script>
    <% @y += 30 %>
  <% end %>
  
<% end %>
<hr />
<%= render "navwrapper" %>

<script>
  $('#download').click(function(){
    var base64 = canvas.toDataURL();
    Canvas2Image.saveAsPNG(canvas);
  });
  $('#download-link').click(function(){
    var base64 = canvas.toDataURL();
    Canvas2Image.saveAsPNG(canvas);
  });  
</script>

app/views/users/new.html.erb
<div id="login">
  <h1>Create an account</h1>
    <%= form_for @user do |f|%>
      <% if @user.errors.any? %>
        <div>
          <h2>Error</h2>
        </div>  
      <% end %>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </p>  
  
      <%= image_submit_tag("save.png", :id => 'download', :class => "icon") %>
    <% end %>
</div>